// Generated by Zoid ZML codegen. Do not edit manually.
use gpui::*;
use gpui_kit::component::*;

/// The window title declared in the UI source.
pub(super) fn window_title() -> SharedString {
    "Slurminal".into()
}

/// `WindowOptions` for this application's main window.
pub(super) fn window_options(cx: &mut App) -> WindowOptions {
    let size = size(px(720.0), px(480.0));
    let bounds = Bounds::centered(None, size, cx);
    WindowOptions {
        window_bounds: Some(WindowBounds::Windowed(bounds)),
        titlebar: Some(TitlebarOptions {
            title: Some(window_title()),
            ..Default::default()
        }),
        kind: WindowKind::Normal,
        is_resizable: true,
        ..Default::default()
    }
}

/// Applies the UI source's window-level presentation props to the
/// global gpui-component theme. Call once from `main`, after
/// `gpui_kit::init(cx)`.
pub(super) fn configure_theme(cx: &mut App) {
    Theme::set_scrollbar_mode(scroll::ScrollbarMode::Scrolling, cx);
    Theme::global_mut(cx).notification.placement = Anchor::BottomRight;
}
