// Generated by Zoid ZML codegen. Do not edit manually.
use gpui::*;
use gpui_kit::component::*;
use zoid_gpui::*;

pub(super) fn zml_layout(
    _window: &mut Window,
    _cx: &mut Context<impl Render>,
) -> impl IntoElement {
    div()
        .flex()
        .flex_col()
        .child(
            div().id("node-1").flex().flex_col()
        )
}
