mod menu_actions;
#[cfg(not(target_os = "macos"))]
mod menu_bar;

// The editable content region of the main window. Its source of truth is
// `ui/app.json`; this module is regenerated by Zoid on export (File ▸ Export in
// the editor). Declared here at the crate root so `#[path]` resolves against
// `src/`.
#[path = "ui/zml_layout.rs"]
mod zml_layout;

// Window-level props from the same UI source: the main window's size, kind and
// resizability. Also regenerated on export.
#[path = "ui/window_options.rs"]
mod window_options;

mod settings;

use gpui::{
    App, Bounds, Context, SharedString, TitlebarOptions, Window, WindowBounds,
    WindowOptions, div, prelude::*, px, size,
};
use gpui_kit::component::*;

use menu_actions::{CloseWindow, NewWindow, OpenPreferences, ToggleTheme, install_app_menus};
#[cfg(not(target_os = "macos"))]
use menu_actions::{MenuNavLeft, MenuNavRight, OpenAppMenu};
#[cfg(not(target_os = "macos"))]
use menu_bar::AppMenuBar;
use settings::AppSettings;

/// Root view for the main application window.
struct RootView {
    project_name: SharedString,
    #[cfg(not(target_os = "macos"))]
    menu_bar: gpui::Entity<AppMenuBar>,
}

impl RootView {
    /// Creates a new `RootView`.
    ///
    /// Colours are not stored on the view: they are read from `cx.theme()` at
    /// render time, so a theme change repaints every view without any of them
    /// holding a stale copy.
    fn new(project_name: impl Into<SharedString>, cx: &mut Context<Self>) -> Self {
        let _ = cx;
        Self {
            project_name: project_name.into(),
            #[cfg(not(target_os = "macos"))]
            menu_bar: cx.new(|cx| AppMenuBar::new(menu_actions::build_in_window_menus(), cx)),
        }
    }
}

impl Render for RootView {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let theme = cx.theme();
        let mode_label: SharedString = if theme.mode.is_dark() {
            "Theme: Dark".into()
        } else {
            "Theme: Light".into()
        };
        let (background, foreground, muted, accent) = (
            theme.background,
            theme.foreground,
            theme.muted_foreground,
            theme.primary,
        );

        let content = div()
            .flex()
            .flex_col()
            .flex_grow(1.0)
            .justify_center()
            .items_center()
            .gap_3()
            .bg(background)
            .text_color(foreground)
            .child(
                div()
                    .text_xl()
                    .font_weight(gpui::FontWeight::MEDIUM)
                    .child(format!("Welcome to {}", self.project_name)),
            )
            .child(
                div()
                    .text_sm()
                    .text_color(muted)
                    .child("A menubar GPUI app generated by Zoid."),
            )
            .child(div().text_sm().text_color(accent).child(mode_label))
            // Everything above is hand-written chrome. This child is the part
            // the Zoid canvas owns, regenerated from `ui/app.json` on export.
            .child(zml_layout::zml_layout(window, cx));

        let root = div()
            .key_context("app")
            // `Theme::change` swaps the global palette; every view re-reads it on
            // the next paint, so there is no per-view theme state to update here.
            .on_action(cx.listener(|_view, _: &ToggleTheme, window, cx| {
                let next = if cx.theme().mode.is_dark() {
                    ThemeMode::Light
                } else {
                    ThemeMode::Dark
                };
                Theme::change(next, Some(window), cx);
                cx.notify();
            }))
            .on_action(cx.listener(|_view, _: &CloseWindow, window, _cx| {
                window.remove_window();
            }))
            .flex()
            .flex_col()
            .size_full()
            .bg(background)
            .text_color(foreground);

        #[cfg(not(target_os = "macos"))]
        let root = {
            let menu = self.menu_bar.clone();
            root.on_action(cx.listener(|this, _: &OpenAppMenu, window, cx| {
                this.menu_bar.update(cx, |bar, cx| bar.open_first(window, cx));
            }))
            .on_action(cx.listener(|this, _: &MenuNavLeft, window, cx| {
                this.menu_bar
                    .update(cx, |bar, cx| bar.navigate_left(window, cx));
            }))
            .on_action(cx.listener(|this, _: &MenuNavRight, window, cx| {
                this.menu_bar
                    .update(cx, |bar, cx| bar.navigate_right(window, cx));
            }))
            .child(menu)
        };

        root.child(content)
    }
}

fn open_main_window(cx: &mut App) {
    // Size, kind and resizability come from `ui/app.json` via the generated
    // module, so they are canvas-editable rather than hard-coded here.
    let options = window_options::window_options(cx);
    let result = cx.open_window(
        options,
        |window, cx| {
            let view = cx.new(|cx| RootView::new("Slurminal", cx));
            cx.new(|cx| Root::new(view, window, cx).bg(cx.theme().background))
        },
    );

    if let Err(error) = result {
        eprintln!("failed to open main window: {error}");
        cx.quit();
    }
}

fn open_preferences_window(cx: &mut App) {
    let bounds = Bounds::centered(None, size(px(480.0), px(320.0)), cx);
    let result = cx.open_window(
        WindowOptions {
            window_bounds: Some(WindowBounds::Windowed(bounds)),
            titlebar: Some(TitlebarOptions {
                title: Some(SharedString::from("Preferences")),
                appears_transparent: false,
                ..Default::default()
            }),
            ..Default::default()
        },
        |window, cx| {
            let view = cx.new(|_cx| PreferencesView);
            cx.new(|cx| Root::new(view, window, cx).bg(cx.theme().background))
        },
    );

    if let Err(error) = result {
        eprintln!("failed to open preferences window: {error}");
    }
}

/// Simple preferences window view.
struct PreferencesView;

impl Render for PreferencesView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let theme = cx.theme();
        div()
            .flex()
            .flex_col()
            .size_full()
            .p_4()
            .bg(theme.background)
            .text_color(theme.foreground)
            .child(div().text_xl().mb_4().child("Preferences"))
            .child(
                div()
                    .text_color(theme.muted_foreground)
                    .child("No preferences are available yet."),
            )
    }
}

fn main() {
    gpui_kit::application().run(|cx: &mut App| {
        gpui_kit::init(cx);

        // Scrollbar and toast placement come from the UI source's window props,
        // so this must run after `init` (which installs the theme) and before
        // any window opens.
        window_options::configure_theme(cx);

        cx.activate(true);
        install_app_menus(cx);

        let settings = AppSettings::load_from_file("settings.toml").unwrap_or_default();

        // Seed the global palette from the persisted preference. Everything
        // downstream reads `cx.theme()`, so this is the only place the stored
        // mode is applied.
        Theme::change(settings.appearance.theme, None, cx);

        // Neither handler needs the settings any more: the theme lives in the
        // global palette, so a new window inherits it automatically.
        cx.on_action(|_: &NewWindow, cx: &mut App| open_main_window(cx));
        cx.on_action(|_: &OpenPreferences, cx: &mut App| open_preferences_window(cx));

        open_main_window(cx);
    });
}

#[cfg(test)]
mod tests {
    use gpui::TestAppContext;

    use super::*;
    use settings::AppearanceSettings;

    #[gpui::test]
    fn root_view_renders_with_the_project_name(cx: &mut TestAppContext) {
        let view = cx.update(|cx| {
            gpui_kit::init(cx);
            cx.new(|cx| RootView::new("Slurminal", cx))
        });

        view.read_with(cx, |view, _| {
            assert_eq!(view.project_name.as_ref(), "Slurminal");
        });
    }

    #[gpui::test]
    fn toggling_the_theme_switches_the_global_mode(cx: &mut TestAppContext) {
        cx.update(|cx| {
            gpui_kit::init(cx);

            Theme::change(ThemeMode::Light, None, cx);
            assert!(!cx.theme().mode.is_dark());

            Theme::change(ThemeMode::Dark, None, cx);
            assert!(cx.theme().mode.is_dark());
        });
    }

    #[gpui::test]
    fn settings_seed_the_global_theme(cx: &mut TestAppContext) {
        let settings = AppSettings {
            appearance: AppearanceSettings {
                theme: ThemeMode::Light,
            },
            ..AppSettings::default()
        };

        cx.update(|cx| {
            gpui_kit::init(cx);
            Theme::change(settings.appearance.theme, None, cx);
            assert!(!cx.theme().mode.is_dark());
        });
    }
}
