mod menu_actions;
#[cfg(not(target_os = "macos"))]
mod menu_bar;

// The editable content region of the main window. Its source of truth is
// `ui/app.json`; this module is regenerated by Zoid on export (File ▸ Export in
// the editor). Declared here at the crate root so `#[path]` resolves against
// `src/`.
#[path = "ui/zml_layout.rs"]
mod zml_layout;

// Window-level props from the same UI source: the main window's size, kind and
// resizability. Also regenerated on export.
#[path = "ui/window_options.rs"]
mod window_options;

mod settings;

use std::sync::mpsc::{Receiver, TryRecvError};
use std::time::Duration;

use gpui::{
    AnyElement, App, Bounds, Context, Entity, SharedString, Subscription, Task, TitlebarOptions,
    Window, WindowBounds, WindowOptions, div, prelude::*, px, size,
};
use gpui_kit::component::*;

use menu_actions::{CloseWindow, NewWindow, OpenPreferences, ToggleTheme, install_app_menus};
#[cfg(not(target_os = "macos"))]
use menu_actions::{MenuNavLeft, MenuNavRight, OpenAppMenu};
#[cfg(not(target_os = "macos"))]
use menu_bar::AppMenuBar;
use settings::AppSettings;

// The terminal: everything below comes from the component's public
// interface only. The view owns the emulator core; the PTY stays app-owned
// per the terminal component contract.
use zoid_slurminal_component::pty::{PtyConfig, PtySession, pump_to_channel};
use zoid_slurminal_component::surface::{TerminalEvent, TerminalView};

/// Grid size the shell starts with. Fixed for now: viewport-driven resize
/// (`grid_dims_for_viewport` + `PtySession::resize`) is a follow-up.
const TERMINAL_COLS: u16 = 80;
/// See [`TERMINAL_COLS`].
const TERMINAL_ROWS: u16 = 24;

/// How often queued PTY output is drained into the terminal (~120 Hz).
const PUMP_POLL_INTERVAL: Duration = Duration::from_millis(8);

/// How long teardown waits for the killed shell to be reaped.
const REAP_TIMEOUT: Duration = Duration::from_millis(500);

/// A live shell: the retained view plus the PTY session behind it.
///
/// Output: a pump thread forwards child output to `rx`, and a main-thread
/// task drains it into the `!Send` terminal via `TerminalView::feed`.
/// Input: the view emits `TerminalEvent::Input` (keys and VT query
/// responses), which the subscription writes to the PTY.
struct TerminalPane {
    view: Entity<TerminalView>,
    session: PtySession,
    rx: Receiver<Vec<u8>>,
    _input: Subscription,
    _poll: Task<()>,
}

/// Root view for the main application window: a menu bar and a terminal.
struct RootView {
    project_name: SharedString,
    #[cfg(not(target_os = "macos"))]
    menu_bar: gpui::Entity<AppMenuBar>,
    /// The live shell. `None` until [`RootView::start_terminal`] runs —
    /// constructing the view (including in `cargo test`) never spawns a
    /// process; only `open_main_window` starts one.
    terminal: Option<TerminalPane>,
    /// Why the shell could not start, shown in place of the terminal.
    spawn_error: Option<SharedString>,
    /// Kill-and-reap the shell when the window's view is released.
    _release: Subscription,
}

impl RootView {
    /// Creates a new `RootView` with no shell attached.
    ///
    /// Colours are not stored on the view: they are read from `cx.theme()` at
    /// render time, so a theme change repaints every view without any of them
    /// holding a stale copy.
    fn new(project_name: impl Into<SharedString>, cx: &mut Context<Self>) -> Self {
        Self {
            project_name: project_name.into(),
            #[cfg(not(target_os = "macos"))]
            menu_bar: cx.new(|cx| AppMenuBar::new(menu_actions::build_in_window_menus(), cx)),
            terminal: None,
            spawn_error: None,
            _release: cx.on_release(|view, _cx| view.close_terminal()),
        }
    }

    /// Spawn the default shell in a PTY, wire it to a terminal view, and
    /// give that view keyboard focus.
    ///
    /// A spawn failure leaves `terminal` as `None` and records the error
    /// for the window to show.
    fn start_terminal(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        if self.terminal.is_some() {
            return;
        }
        let config = PtyConfig::shell(TERMINAL_COLS, TERMINAL_ROWS);
        let spawned = PtySession::spawn(&config)
            .and_then(|session| session.clone_reader().map(|reader| (session, reader)));
        let (session, reader) = match spawned {
            Ok(pair) => pair,
            Err(error) => {
                self.spawn_error = Some(format!("Could not start a shell: {error}").into());
                cx.notify();
                return;
            }
        };
        let (tx, rx) = std::sync::mpsc::channel();
        std::thread::spawn(move || pump_to_channel(reader, tx));

        let view = cx.new(|_cx| TerminalView::new());
        let input = cx.subscribe(&view, |root, _view, event: &TerminalEvent, _cx| {
            let TerminalEvent::Input(bytes) = event;
            if let Some(pane) = root.terminal.as_mut() {
                // A failed write means the shell is gone; the poll task
                // notices the exit and closes the window.
                let _ = pane.session.write_all(bytes);
            }
        });
        let poll = cx.spawn_in(window, async move |root, cx| {
            loop {
                cx.background_executor().timer(PUMP_POLL_INTERVAL).await;
                let alive = root
                    .update_in(cx, |root, window, cx| root.pump(window, cx))
                    .unwrap_or(false);
                if !alive {
                    break;
                }
            }
        });

        view.update(cx, |view, cx| view.focus(window, cx));
        self.spawn_error = None;
        self.terminal = Some(TerminalPane {
            view,
            session,
            rx,
            _input: input,
            _poll: poll,
        });
        cx.notify();
    }

    /// Drain queued output into the terminal; close the window once the
    /// shell has exited. Returns whether the shell is still running.
    fn pump(&mut self, window: &mut Window, cx: &mut Context<Self>) -> bool {
        let Some(pane) = self.terminal.as_mut() else {
            return false;
        };
        let mut disconnected = false;
        loop {
            match pane.rx.try_recv() {
                Ok(chunk) => pane.view.update(cx, |view, cx| view.feed(&chunk, cx)),
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Disconnected) => {
                    disconnected = true;
                    break;
                }
            }
        }
        // ConPTY never delivers EOF while the master is open, so child exit
        // is the reliable signal; a disconnected pump is the other one.
        let alive = !disconnected && pane.session.is_alive().unwrap_or(false);
        if !alive {
            self.close_terminal();
            window.remove_window();
        }
        alive
    }

    /// Kill the shell and drop the terminal state.
    ///
    /// Kill-then-reap is explicit rather than relying on the session's drop
    /// backstop, which would leave a zombie until this process exits. The
    /// pump thread exits on its own once the session's master end closes.
    fn close_terminal(&mut self) {
        if let Some(mut pane) = self.terminal.take() {
            let _ = pane.session.kill();
            let _ = pane.session.wait_for_exit(REAP_TIMEOUT);
        }
    }

    /// The terminal, or the reason there is none.
    fn render_terminal(&self, cx: &Context<Self>) -> AnyElement {
        match (&self.terminal, &self.spawn_error) {
            (Some(pane), _) => pane.view.clone().into_any_element(),
            (None, Some(error)) => div()
                .text_sm()
                .text_color(cx.theme().danger)
                .child(error.clone())
                .into_any_element(),
            (None, None) => div()
                .text_sm()
                .text_color(cx.theme().muted_foreground)
                .child(format!("{}: starting shell…", self.project_name))
                .into_any_element(),
        }
    }
}

impl Render for RootView {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let theme = cx.theme();
        let (background, foreground) = (theme.background, theme.foreground);

        let content = div()
            .id("slurminal-terminal")
            .flex()
            .flex_col()
            .flex_grow(1.0)
            .min_h_0()
            .overflow_hidden()
            .p_2()
            .bg(background)
            .text_color(foreground)
            // The part the Zoid canvas owns, regenerated from `ui/app.json`
            // on export. Empty by default; the terminal is the app's content.
            .child(zml_layout::zml_layout(window, cx))
            .child(self.render_terminal(cx));

        let root = div()
            .key_context("app")
            // `Theme::change` swaps the global palette; every view re-reads it on
            // the next paint, so there is no per-view theme state to update here.
            .on_action(cx.listener(|_view, _: &ToggleTheme, window, cx| {
                let next = if cx.theme().mode.is_dark() {
                    ThemeMode::Light
                } else {
                    ThemeMode::Dark
                };
                Theme::change(next, Some(window), cx);
                cx.notify();
            }))
            .on_action(cx.listener(|_view, _: &CloseWindow, window, _cx| {
                window.remove_window();
            }))
            .flex()
            .flex_col()
            .size_full()
            .bg(background)
            .text_color(foreground);

        #[cfg(not(target_os = "macos"))]
        let root = {
            let menu = self.menu_bar.clone();
            root.on_action(cx.listener(|this, _: &OpenAppMenu, window, cx| {
                this.menu_bar.update(cx, |bar, cx| bar.open_first(window, cx));
            }))
            .on_action(cx.listener(|this, _: &MenuNavLeft, window, cx| {
                this.menu_bar
                    .update(cx, |bar, cx| bar.navigate_left(window, cx));
            }))
            .on_action(cx.listener(|this, _: &MenuNavRight, window, cx| {
                this.menu_bar
                    .update(cx, |bar, cx| bar.navigate_right(window, cx));
            }))
            .child(menu)
        };

        root.child(content)
    }
}

fn open_main_window(cx: &mut App) {
    // Size, kind and resizability come from `ui/app.json` via the generated
    // module, so they are canvas-editable rather than hard-coded here.
    let options = window_options::window_options(cx);
    let result = cx.open_window(
        options,
        |window, cx| {
            let view = cx.new(|cx| RootView::new("Slurminal", cx));
            // A terminal app opens with a live shell. Spawning here, not in
            // `RootView::new`, keeps view construction (and tests) headless.
            view.update(cx, |view, cx| view.start_terminal(window, cx));
            cx.new(|cx| Root::new(view, window, cx).bg(cx.theme().background))
        },
    );

    if let Err(error) = result {
        eprintln!("failed to open main window: {error}");
        cx.quit();
    }
}

fn open_preferences_window(cx: &mut App) {
    let bounds = Bounds::centered(None, size(px(480.0), px(320.0)), cx);
    let result = cx.open_window(
        WindowOptions {
            window_bounds: Some(WindowBounds::Windowed(bounds)),
            titlebar: Some(TitlebarOptions {
                title: Some(SharedString::from("Preferences")),
                appears_transparent: false,
                ..Default::default()
            }),
            ..Default::default()
        },
        |window, cx| {
            let view = cx.new(|_cx| PreferencesView);
            cx.new(|cx| Root::new(view, window, cx).bg(cx.theme().background))
        },
    );

    if let Err(error) = result {
        eprintln!("failed to open preferences window: {error}");
    }
}

/// Simple preferences window view.
struct PreferencesView;

impl Render for PreferencesView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let theme = cx.theme();
        div()
            .flex()
            .flex_col()
            .size_full()
            .p_4()
            .bg(theme.background)
            .text_color(theme.foreground)
            .child(div().text_xl().mb_4().child("Preferences"))
            .child(
                div()
                    .text_color(theme.muted_foreground)
                    .child("No preferences are available yet."),
            )
    }
}

fn main() {
    gpui_kit::application().run(|cx: &mut App| {
        gpui_kit::init(cx);

        // Scrollbar and toast placement come from the UI source's window props,
        // so this must run after `init` (which installs the theme) and before
        // any window opens.
        window_options::configure_theme(cx);

        cx.activate(true);
        install_app_menus(cx);

        let settings = AppSettings::load_from_file("settings.toml").unwrap_or_default();

        // Seed the global palette from the persisted preference. Everything
        // downstream reads `cx.theme()`, so this is the only place the stored
        // mode is applied.
        Theme::change(settings.appearance.theme, None, cx);

        // Neither handler needs the settings any more: the theme lives in the
        // global palette, so a new window inherits it automatically.
        cx.on_action(|_: &NewWindow, cx: &mut App| open_main_window(cx));
        cx.on_action(|_: &OpenPreferences, cx: &mut App| open_preferences_window(cx));

        open_main_window(cx);
    });
}

#[cfg(test)]
mod tests {
    use gpui::TestAppContext;

    use super::*;
    use settings::AppearanceSettings;

    #[gpui::test]
    fn root_view_renders_with_the_project_name(cx: &mut TestAppContext) {
        let view = cx.update(|cx| {
            gpui_kit::init(cx);
            cx.new(|cx| RootView::new("Slurminal", cx))
        });

        view.read_with(cx, |view, _| {
            assert_eq!(view.project_name.as_ref(), "Slurminal");
        });
    }

    #[gpui::test]
    fn constructing_the_root_view_spawns_no_shell(cx: &mut TestAppContext) {
        let view = cx.update(|cx| {
            gpui_kit::init(cx);
            cx.new(|cx| RootView::new("Slurminal", cx))
        });

        view.read_with(cx, |view, _| {
            assert!(view.terminal.is_none());
            assert!(view.spawn_error.is_none());
        });
    }

    #[gpui::test]
    fn toggling_the_theme_switches_the_global_mode(cx: &mut TestAppContext) {
        cx.update(|cx| {
            gpui_kit::init(cx);

            Theme::change(ThemeMode::Light, None, cx);
            assert!(!cx.theme().mode.is_dark());

            Theme::change(ThemeMode::Dark, None, cx);
            assert!(cx.theme().mode.is_dark());
        });
    }

    #[gpui::test]
    fn settings_seed_the_global_theme(cx: &mut TestAppContext) {
        let settings = AppSettings {
            appearance: AppearanceSettings {
                theme: ThemeMode::Light,
            },
            ..AppSettings::default()
        };

        cx.update(|cx| {
            gpui_kit::init(cx);
            Theme::change(settings.appearance.theme, None, cx);
            assert!(!cx.theme().mode.is_dark());
        });
    }
}
